httpbeat:
  hosts:
    -
      schedule: "@every 3h"
      url: "https://api.clashroyale.com/v1/locations/global/rankings/players"
      method: get
      
      headers:
        Accept: application/json
        authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImY5Njc0OGE5LTgyZmQtNDA2MS1hNzVmLTBkZDMyYTM3YWM3OCIsImlhdCI6MTYzOTM4ODMyNSwic3ViIjoiZGV2ZWxvcGVyLzk1YjY5ZTE5LTgzOGUtMzg0Ny03ZDdiLTUzODY4OWQyZDliZiIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyI5Mi4xODQuMTAyLjE4OSIsIjEzNC4yMTQuMjAyLjM3Il0sInR5cGUiOiJjbGllbnQifV19.9gwE0wAd9Syk_9v8qHGv1nVd6DG5-nY9qml7dMviyXOWLLKro2KdQw_nZCMJGi03aVuATpKEbCqX_3P-5RnztA
             
      output_format: json
  
output.elasticsearch:
  # Avec l'ordi de départ
  # hosts: ["localhost:9201"]
  hosts: ["tc405-112-12.insa-lyon.fr:9201"]
  index: "clashroyalefinal"
  template.enabled: false

# output.file:
#   enabled: true

#   path: "~/Desktop"
#   number_of_files: 1
      
